modLoader = "javafml"
loaderVersion = "[35,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL = "https://github.com/Aethli/mineauth/issues"
[[mods]]
modId = "mineauth"
version = "${file.jarVersion}"
displayName = "mineauth"
updateJSONURL = "https://raw.githubusercontent.com/AethLi/mineauth/master/update.json"
displayURL = "https://github.com/Aethli/mineauth"
logoFile = "examplemod.png"
credits = ""
authors = "aethli"
description = "just auth"
[[dependencies.mineauth]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mineauth]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1,)"
ordering = "NONE"
side = "BOTH"
